/* stdafx.cpp : source file that includes just the standard includes */
/* ex18a.pch will be the pre-compiled header */
/* stdafx.obj will contain the pre-compiled type information */

/* this (including the comments above) was generated by Visual Studio */
/* not sure what this file is used for */

#include "stdafx.h"

/* TODO: reference any additional headers you need in STDAFX.H */
/* and not in this file */
