/* stdafx.h : include file for standard system include files, */
/* or project specific include files that are used frequently, but */
/* are changed infrequently */
/* */

/* #pragma once is C and C++, non-standard but widely supported, autogenerated by Visual Studio */
#pragma once

#include "targetver.h"

#include <stdio.h>
#include <tchar.h>



/* TODO: reference additional headers your program requires here */
